import type { DFIRDocument } from "@docuforge/core";

export interface GeneratedFile {
	fileName: string;
	content: string;
}

/**
 * Human-first Markdown generator for DocuForge.
 *
 * Important: the generator only renders information available in DFIR.
 * It does not invent descriptions, response schemas, relationships, etc.
 */
export function generateMarkdown(doc: DFIRDocument): GeneratedFile[] {
	return [
		{ fileName: "README.md", content: renderReadme(doc) },
		{ fileName: "ARCHITECTURE.md", content: renderArchitecture(doc) },
		{ fileName: "API.md", content: renderApi(doc) },
		{ fileName: "ROUTES.md", content: renderRoutes(doc) },
		{ fileName: "DATABASE.md", content: renderDatabase(doc) },
		{ fileName: "MODELS.md", content: renderModels(doc) },
		{ fileName: "CONTROLLERS.md", content: renderControllers(doc) },
		{ fileName: "DEPENDENCIES.md", content: renderDependencies(doc) },
	];
}

/**
 * Main output: one complete, readable documentation portal in Markdown.
 */
export function generateCombinedMarkdown(doc: DFIRDocument): GeneratedFile {
	const sections = [
		renderOverview(doc),
		renderTechnologyStack(doc),
		renderProjectMap(doc),
		renderArchitecture(doc),
		renderApplicationFlow(doc),
		renderApi(doc),
		renderRoutes(doc),
		renderDatabase(doc),
		renderModels(doc),
		renderControllers(doc),
		renderDependencies(doc),
		// renderCoverage(doc),
	];

	const toc = [
		"## 📑 Table of Contents",
		"",
		"- [📊 Project Overview](#-project-overview)",
		"- [🛠️ Technology Stack](#️-technology-stack)",
		"- [🗺️ Project Map](#️-project-map)",
		"- [🏗️ Architecture](#️-architecture)",
		"- [🔄 Application Flow](#-application-flow)",
		"- [🌐 API Reference](#-api-reference)",
		"- [🛣️ Routes](#️-routes)",
		"- [🗄️ Database](#️-database)",
		"- [🧩 Models](#-models)",
		"- [🎮 Controllers](#-controllers)",
		"- [📦 Dependencies](#-dependencies)",
		"- [📈 Documentation Coverage](#-documentation-coverage)",
		"",
		"---",
		"",
	].join("\n");

	const header = [
		`# ${safe(doc.project.name)}`,
		"",
		"> 📚 Automatically generated by **DocuForge**.",
		`> Generated on \`${safe(doc.generatedAt)}\`.`,
		"",
		quickFacts(doc),
		"",
		"> ℹ️ This documentation is generated from the project's DFIR representation. " +
			"Information that cannot be determined statically is explicitly marked as unavailable.",
		"",
		toc,
	].join("\n");

	return {
		fileName: "DOCUMENTATION.md",
		content: `${header}${sections.join("\n\n---\n\n")}\n`,
	};
}

function renderOverview(doc: DFIRDocument): string {
	const auth = doc.routes.filter((r) => r.requiresAuth).length;
	const publicRoutes = doc.routes.length - auth;
	const mappedModels = doc.models.filter((m) => Boolean(m.table)).length;

	const lines = [
		"# 📊 Project Overview",
		"",
		`## ${safe(doc.project.name)}`,
		"",
		`**${safe(doc.project.name)}** is a **${safe(doc.project.language)}** project built with ` +
			`**${safe(doc.project.framework ?? "an unrecognized framework")}**` +
			`${doc.project.frameworkVersion ? ` \`${safe(doc.project.frameworkVersion)}\`` : ""}.`,
		"",
		"### 📌 At a Glance",
		"",
		statsTable(doc),
		"",
	];

	if (doc.routes.length) {
		lines.push(
			"### 🌐 API Surface",
			"",
			`The project exposes **${doc.routes.length} route${plural(doc.routes.length)}** across ` +
				`**${doc.controllers.length} controller${plural(doc.controllers.length)}**.`,
			"",
			`- 🌍 Public routes: **${publicRoutes}**`,
			`- 🔒 Authenticated routes: **${auth}**`,
			`- 🧩 Models mapped to database tables: **${mappedModels}**`,
			"",
		);
	}

	if (doc.controllers.length) {
		lines.push("### 🧭 Main Components", "");
		for (const controller of doc.controllers) {
			const routes = doc.routes.filter((r) => r.controllerId === controller.id);
			const actions = controller.methods
				.map((m) => `\`${safe(m.name)}()\``)
				.join(", ");
			lines.push(
				`- **${safe(controller.name.replace(/Controller$/, ""))}** — ` +
					`${controller.methods.length} action${plural(controller.methods.length)}, ` +
					`${routes.length} mapped route${plural(routes.length)}.` +
					(actions ? ` Actions: ${actions}.` : ""),
			);
		}
		lines.push("");
	}

	if (doc.models.some((m) => m.relationships.length)) {
		lines.push("### 🔗 Key Relationships", "");
		for (const model of doc.models) {
			for (const rel of model.relationships) {
				lines.push(
					`- **${safe(model.name)}** — \`${safe(rel.type)}\` → **${safe(rel.target)}**`,
				);
			}
		}
		lines.push("");
	}

	return trim(lines.join("\n"));
}

function renderTechnologyStack(doc: DFIRDocument): string {
	const p = doc.project;
	return [
		"# 🛠️ Technology Stack",
		"",
		"| Category | Detected technology |",
		"|---|---|",
		`| Language | \`${safe(p.language)}\` |`,
		`| Framework | \`${safe(p.framework ?? "Not detected")}${p.frameworkVersion ? ` ${safe(p.frameworkVersion)}` : ""}\` |`,
		`| Package manager | \`${safe(p.packageManager ?? "Not detected")}\` |`,
		"",
		"> Missing values are shown as `Not detected`; DocuForge does not guess technology choices.",
	].join("\n");
}

function renderProjectMap(doc: DFIRDocument): string {
	const lines = [
		"# 🗺️ Project Map",
		"",
		"A compact map of the components detected by DocuForge.",
		"",
		"```text",
		"PROJECT",
		"├── Routes",
		`│   └── ${doc.routes.length} route${plural(doc.routes.length)}`,
		"├── Controllers",
		`│   └── ${doc.controllers.length} controller${plural(doc.controllers.length)}`,
		"├── Services",
		`│   └── ${doc.services.length} service${plural(doc.services.length)}`,
		"├── Models",
		`│   └── ${doc.models.length} model${plural(doc.models.length)}`,
		"├── Database",
		`│   └── ${doc.database.tables.length} table${plural(doc.database.tables.length)}`,
		"└── Dependencies",
		`    └── ${doc.dependencies.length} dependenc${doc.dependencies.length === 1 ? "y" : "ies"}`,
		"```",
		"",
	];

	if (doc.controllers.length) {
		lines.push(
			"### Controller → Route Map",
			"",
			"| Component | Actions | Routes |",
			"|---|---:|---:|",
		);
		for (const controller of doc.controllers) {
			const routeCount = doc.routes.filter(
				(r) => r.controllerId === controller.id,
			).length;
			lines.push(
				`| \`${safe(controller.name)}\` | ${controller.methods.length} | ${routeCount} |`,
			);
		}
		lines.push("");
	}

	return trim(lines.join("\n"));
}

function renderArchitecture(doc: DFIRDocument): string {
	const lines = ["# 🏗️ Architecture", "", "## Component Relationships", ""];

	if (!doc.routes.length && !doc.relationships.length) {
		lines.push("> No architecture relationships were detected automatically.");
		return lines.join("\n");
	}

	lines.push("```mermaid", "flowchart TD");

	for (const route of doc.routes) {
		if (!route.controllerId) continue;
		const controller = doc.controllers.find((c) => c.id === route.controllerId);
		if (!controller) continue;
		lines.push(
			`  R_${sanitize(route.id)}["${mermaid(`${route.method} ${route.path}`)}"] --> ` +
				`C_${sanitize(controller.id)}["${mermaid(controller.name)}"]`,
		);
	}

	for (const rel of doc.relationships) {
		if (rel.kind === "route->controller") continue;
		lines.push(
			`  N_${sanitize(rel.from)}["${mermaid(rel.from)}"] --> ` +
				`N_${sanitize(rel.to)}["${mermaid(rel.to)}"]`,
		);
	}

	lines.push(
		"```",
		"",
		"### 🧠 How to Read This",
		"",
		"- Route → Controller means an HTTP entry point was mapped to a handler.",
		"- Other arrows are relationships exposed by the scanner.",
		"- Missing arrows do not prove that a relationship does not exist; it may be dynamically resolved or not supported by the current scanner.",
	);

	if (doc.relationships.length) {
		lines.push(
			"",
			"## Detected Relationships",
			"",
			"| From | Relationship | To |",
			"|---|---|---|",
		);
		for (const rel of doc.relationships) {
			lines.push(
				`| \`${safe(rel.from)}\` | \`${safe(rel.kind)}\` | \`${safe(rel.to)}\` |`,
			);
		}
	}

	return trim(lines.join("\n"));
}

function renderApplicationFlow(doc: DFIRDocument): string {
	const lines = [
		"# 🔄 Application Flow",
		"",
		"A framework-neutral view of a typical request represented by the detected project structure.",
		"",
		"```text",
		"Client",
		"  │",
		"  ▼",
		"Route",
		"  │",
		"  ▼",
		"Middleware",
		"  │",
		"  ▼",
		"Controller",
		"  │",
		"  ▼",
		"Domain / persistence layer",
		"  │",
		"  ▼",
		"Database",
		"```",
		"",
	];

	if (doc.routes.length) {
		lines.push("## Example Detected Flows", "");
		for (const route of doc.routes.slice(0, 10)) {
			const controller = route.controllerId
				? doc.controllers.find((c) => c.id === route.controllerId)
				: undefined;
			const handler = controller
				? `${controller.name}@${route.controllerMethod ?? "?"}`
				: "Unmapped handler";
			lines.push(
				`- ${methodBadge(route.method)} \`${safe(route.path)}\` → **${safe(handler)}**`,
			);
		}
		lines.push("");
		if (doc.routes.length > 10) {
			lines.push(
				`> Showing 10 of ${doc.routes.length} routes. See [ROUTES.md](./ROUTES.md) for the full list.`,
				"",
			);
		}
	} else {
		lines.push("> No routes were detected automatically.", "");
	}

	return trim(lines.join("\n"));
}

function renderApi(doc: DFIRDocument): string {
	const lines = [
		"# 🌐 API Reference",
		"",
		"HTTP endpoints detected from the project.",
		"",
	];

	if (!doc.routes.length) {
		lines.push("> No API routes were detected.");
		return lines.join("\n");
	}

	for (const route of doc.routes) {
		const controller = route.controllerId
			? doc.controllers.find((c) => c.id === route.controllerId)
			: undefined;
		const title = route.name
			? humanize(route.name)
			: `${route.method} ${route.path}`;

		lines.push(
			`## ${methodBadge(route.method)} ${safe(title)}`,
			"",
			`**Endpoint:** \`${safe(route.method)} ${safe(route.path)}\``,
			"",
			"| Property | Value |",
			"|---|---|",
			`| Handler | ${controller ? `\`${safe(`${controller.name}@${route.controllerMethod ?? "?"}`)}\`` : "Not mapped"} |`,
			`| Authentication | ${route.requiresAuth ? "🔒 Required" : "🌍 Not detected"} |`,
			`| Middleware | ${route.middleware.length ? route.middleware.map((m) => `\`${safe(m)}\``).join(", ") : "None detected"} |`,
			"",
		);

		lines.push("### Parameters", "");
		if (route.parameters.length) {
			lines.push("| Name | Location | Required |", "|---|---|---|");
			for (const p of route.parameters) {
				lines.push(
					`| \`${safe(p.name)}\` | ${safe(p.in)} | ${p.required ? "Yes" : "No"} |`,
				);
			}
		} else {
			lines.push("No route parameters were detected.");
		}

		lines.push(
			"",
			"### Response",
			"",
			"> Response schema could not be determined automatically from the current DFIR data.",
			"",
		);
	}

	return trim(lines.join("\n"));
}

function renderRoutes(doc: DFIRDocument): string {
	const groups = groupRoutes(doc);
	const lines = [
		"# 🛣️ Routes",
		"",
		`**${doc.routes.length} route${plural(doc.routes.length)}** detected.`,
		"",
	];

	if (!doc.routes.length) {
		lines.push("> No routes were detected.");
		return lines.join("\n");
	}

	for (const [group, routes] of groups) {
		lines.push(
			`## ${safe(group)}`,
			"",
			"| Method | Endpoint | Handler | Auth | Middleware |",
			"|---|---|---|---|---|",
		);

		for (const route of routes) {
			const controller = route.controllerId
				? doc.controllers.find((c) => c.id === route.controllerId)
				: undefined;
			const handler = controller
				? `${controller.name}@${route.controllerMethod ?? "?"}`
				: "-";
			lines.push(
				`| ${methodBadge(route.method)} | \`${safe(route.path)}\` | \`${safe(handler)}\` | ` +
					`${route.requiresAuth ? "🔒" : "🌍"} | ${route.middleware.length ? route.middleware.map((m) => `\`${safe(m)}\``).join(", ") : "-"} |`,
			);
		}
		lines.push("");
	}

	return trim(lines.join("\n"));
}

function renderDatabase(doc: DFIRDocument): string {
	const lines = [
		"# 🗄️ Database",
		"",
		`**${doc.database.tables.length} table${plural(doc.database.tables.length)}** detected.`,
		"",
	];

	if (!doc.database.tables.length) {
		lines.push("> No database tables were detected.");
		return lines.join("\n");
	}

	lines.push("## Entity Overview", "", "```mermaid", "erDiagram");
	for (const table of doc.database.tables) {
		lines.push(`  ${mermaidIdentifier(table.name)} {`);
		for (const col of table.columns.slice(0, 25)) {
			const type = mermaidType(col.type);
			const key = col.isPrimaryKey ? " PK" : col.isForeignKey ? " FK" : "";
			lines.push(`    ${type} ${mermaidIdentifier(col.name)}${key}`);
		}
		lines.push("  }");
	}
	lines.push(
		"```",
		"",
		"> ℹ️ Table and key information is rendered from detected database metadata. Relationship edges are only added when the DFIR exposes them.",
		"",
	);

	for (const table of doc.database.tables) {
		lines.push(
			`## \`${safe(table.name)}\``,
			"",
			"| Column | Type | Nullable | Key |",
			"|---|---|---|---|",
		);
		for (const col of table.columns) {
			const key = col.isPrimaryKey ? "🔑 PK" : col.isForeignKey ? "🔗 FK" : "-";
			lines.push(
				`| \`${safe(col.name)}\` | ${safe(col.type)} | ${col.nullable ? "Yes" : "No"} | ${key} |`,
			);
		}
		lines.push("");
	}

	return trim(lines.join("\n"));
}

function renderModels(doc: DFIRDocument): string {
	const lines = [
		"# 🧩 Models",
		"",
		`**${doc.models.length} model${plural(doc.models.length)}** detected.`,
		"",
	];

	if (!doc.models.length) {
		lines.push("> No models were detected.");
		return lines.join("\n");
	}

	for (const model of doc.models) {
		lines.push(`## ${safe(model.name)}`, "");
		if (model.table)
			lines.push(`**Database table:** \`${safe(model.table)}\``, "");

		lines.push("### Fields", "");
		if (model.fields.length) {
			lines.push(
				"| Field |",
				"|---|",
				...model.fields.map((f) => `| \`${safe(f.name)}\` |`),
				"",
			);
		} else {
			lines.push("No fields were detected.", "");
		}

		lines.push("### Relationships", "");
		if (model.relationships.length) {
			lines.push("| Relationship | Target |", "|---|---|");
			for (const rel of model.relationships) {
				lines.push(`| \`${safe(rel.type)}\` | **${safe(rel.target)}** |`);
			}
		} else {
			lines.push("No model relationships were detected.");
		}
		lines.push("");
	}

	return trim(lines.join("\n"));
}

function renderControllers(doc: DFIRDocument): string {
	const lines = [
		"# 🎮 Controllers",
		"",
		`**${doc.controllers.length} controller${plural(doc.controllers.length)}** detected.`,
		"",
	];

	if (!doc.controllers.length) {
		lines.push("> No controllers were detected.");
		return lines.join("\n");
	}

	for (const controller of doc.controllers) {
		const routes = doc.routes.filter((r) => r.controllerId === controller.id);
		lines.push(
			`## ${safe(controller.name)}`,
			"",
			`**File:** \`${safe(controller.filePath)}\``,
			"",
			"### Actions",
			"",
		);

		if (controller.methods.length) {
			lines.push("| Method | Mapped routes |", "|---|---:|");
			for (const method of controller.methods) {
				const count = routes.filter(
					(r) => r.controllerMethod === method.name,
				).length;
				lines.push(`| \`${safe(method.name)}()\` | ${count} |`);
			}
		} else {
			lines.push("No methods were detected.");
		}

		if (routes.length) {
			lines.push(
				"",
				"### HTTP Endpoints",
				"",
				...routes.map((r) => `- ${methodBadge(r.method)} \`${safe(r.path)}\``),
			);
		}
		lines.push("");
	}

	return trim(lines.join("\n"));
}

function renderDependencies(doc: DFIRDocument): string {
	const internal = doc.dependencies.filter((d) => d.type === "internal");
	const external = doc.dependencies.filter((d) => d.type === "external");

	const lines = [
		"# 📦 Dependencies",
		"",
		`**${doc.dependencies.length} dependenc${
			doc.dependencies.length === 1 ? "y" : "ies"
		}** detected.`,
		"",
		`- Internal: **${internal.length}**`,
		`- External: **${external.length}**`,
		"",
	];

	if (!doc.dependencies.length) {
		lines.push("> No dependencies were detected.");
		return lines.join("\n");
	}

	lines.push("| Package | Version | Type |", "|---|---|---|");

	for (const dep of doc.dependencies) {
		const typeLabel = dep.type === "internal" ? "🔧 Internal" : "📦 External";

		lines.push(
			`| \`${safe(dep.name)}\` | ${safe(
				dep.version ?? "Not specified",
			)} | ${typeLabel} |`,
		);
	}

	return trim(lines.join("\n"));
}

// function renderCoverage(doc: DFIRDocument): string {
// 	const routeCoverage = percentage(
// 		doc.routes.filter((r) => Boolean(r.controllerId)).length,
// 		doc.routes.length,
// 	);
// 	const modelCoverage = percentage(
// 		doc.models.filter((m) => Boolean(m.table)).length,
// 		doc.models.length,
// 	);
// 	const relationshipCoverage = percentage(
// 		doc.models.filter((m) => m.relationships.length > 0).length,
// 		doc.models.length,
// 	);

// 	return [
// 		"# 📈 Documentation Coverage",
// 		"",
// 		"Coverage measures detected structural information, not whether every line of source code has a human-written explanation.",
// 		"",
// 		"| Area | Coverage | Meaning |",
// 		"|---|---:|---|",
// 		`| Route → controller | ${routeCoverage}% | Routes with a detected controller mapping |`,
// 		`| Model → table | ${modelCoverage}% | Models with a detected database table |`,
// 		`| Model relationships | ${relationshipCoverage}% | Models with at least one detected relationship |`,
// 		"",
// 		"> ⚠️ Lower coverage is not necessarily an error. Dynamic code or unsupported framework conventions may simply be outside the current scanner's capabilities.",
// 	].join("\n");
// }

function renderReadme(doc: DFIRDocument): string {
	const overview = renderOverview(doc).replace(
		/^# 📊 Project Overview\n\n?/,
		"",
	);
	return [
		`# ${safe(doc.project.name)}`,
		"",
		"> 📚 Generated by **DocuForge**.",
		"",
		overview,
		"",
		"## 📚 Documentation",
		"",
		"- [Architecture](./ARCHITECTURE.md)",
		"- [API Reference](./API.md)",
		"- [Routes](./ROUTES.md)",
		"- [Database](./DATABASE.md)",
		"- [Models](./MODELS.md)",
		"- [Controllers](./CONTROLLERS.md)",
		"- [Dependencies](./DEPENDENCIES.md)",
		"",
		`> Generated on \`${safe(doc.generatedAt)}\`.`,
	].join("\n");
}

function quickFacts(doc: DFIRDocument): string {
	return [
		"| | |",
		"|---|---|",
		`| **Language** | \`${safe(doc.project.language)}\` |`,
		`| **Framework** | \`${safe(doc.project.framework ?? "Not detected")}${doc.project.frameworkVersion ? ` ${safe(doc.project.frameworkVersion)}` : ""}\` |`,
		`| **Package manager** | \`${safe(doc.project.packageManager ?? "Not detected")}\` |`,
	].join("\n");
}

function statsTable(doc: DFIRDocument): string {
	return [
		"| Component | Count |",
		"|---|---:|",
		`| 🛣️ Routes | **${doc.routes.length}** |`,
		`| 🎮 Controllers | **${doc.controllers.length}** |`,
		`| ⚙️ Services | **${doc.services.length}** |`,
		`| 🧩 Models | **${doc.models.length}** |`,
		`| 🗄️ Database tables | **${doc.database.tables.length}** |`,
		`| 📦 Dependencies | **${doc.dependencies.length}** |`,
	].join("\n");
}

function groupRoutes(doc: DFIRDocument): Map<string, DFIRDocument["routes"]> {
	const groups = new Map<string, DFIRDocument["routes"]>();
	for (const route of doc.routes) {
		const group = routeGroup(route.path);
		if (!groups.has(group)) groups.set(group, []);
		groups.get(group)!.push(route);
	}
	return groups;
}

function routeGroup(path: string): string {
	const value = path.replace(/^\/+/, "");
	if (!value) return "Root";
	const first = value.split("/")[0];
	if (first.toLowerCase() === "api" || first.toLowerCase().startsWith("api-"))
		return "API";
	return humanize(first);
}

function methodBadge(method: string): string {
	const m = method.toUpperCase();
	const icon: Record<string, string> = {
		GET: "🟢",
		POST: "🔵",
		PUT: "🟠",
		PATCH: "🟡",
		DELETE: "🔴",
	};
	return `${icon[m] ?? "⚪"} \`${safe(m)}\``;
}

function humanize(value: string): string {
	return value
		.replace(/([a-z])([A-Z])/g, "$1 $2")
		.replace(/[_-]+/g, " ")
		.replace(/\s+/g, " ")
		.trim()
		.replace(/\b\w/g, (c) => c.toUpperCase());
}

function mermaidIdentifier(value: string): string {
	const result = value.replace(/[^A-Za-z0-9_]/g, "_");
	return /^[A-Za-z_]/.test(result) ? result : `T_${result}`;
}

function mermaidType(type: string): string {
	const value = type.toLowerCase();
	if (value.includes("int")) return "int";
	if (
		value.includes("decimal") ||
		value.includes("float") ||
		value.includes("double")
	)
		return "float";
	if (value.includes("bool")) return "boolean";
	if (value.includes("date") || value.includes("time")) return "datetime";
	return "string";
}

function mermaid(value: string): string {
	return value.replace(/"/g, '\\"').replace(/\r?\n/g, " ");
}

function sanitize(value: string): string {
	const result = value.replace(/[^A-Za-z0-9_]/g, "_");
	return result || "node";
}

function safe(value: string): string {
	return value.replace(/[|`]/g, "\\$&").replace(/\r?\n/g, " ");
}

function percentage(part: number, total: number): number {
	return total ? Math.round((part / total) * 100) : 0;
}

function plural(n: number): string {
	return n === 1 ? "" : "s";
}

function trim(value: string): string {
	return value.replace(/\n+$/g, "");
}
